[theme]
primaryColor = "#F63366"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#31333F"
textColor = "#FAFAFA"
font = "sans serif"
base = "light"

[server]
headless = true
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[ui]
hideTopBar = true

[runner]
fastReruns = true

[logger]
level = "error"

